### ISSUE TITLE
Deploy to PyPi

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-server-python#30]

**Comment by dbrgn** [comment]
Do you mean on every push? I wouldn't do that. Instead, create a script or instruction textfile that will also add signatures on upload. And then upload using twine. You can't automate that :)

https://packaging.python.org/distributing/#upload-your-distributions

**Comment by lgrahl** [comment]
My plan was on new releases only. Will go through that document. :)

**Comment by dbrgn** [comment]
You can also take a look at https://github.com/dbrgn/result/blob/master/RELEASING.md for reference.

**Comment by lgrahl** [comment]
We'll deploy once #37 has been merged.

**Comment by dbrgn** [comment]
CLI help says:

>   -k, --key PATH               Path to a or a hex-encoded private permanent key of the server (e.g.a NaCl private key).

But hex encoded strings don't seem to be accepted.

**Comment by lgrahl** [comment]
Changed my mind, we'll deploy once the protocol has been released (soon). :)

**Comment by lgrahl** [comment]
https://pypi.python.org/pypi/saltyrtc.server
