### ISSUE TITLE
s/SSL/TLS/

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-server-python#63]
We should rename the `--sslcert` and `--sslkey` options to `--tlscert` and `--tlskey`. Similarly, the `-sk` and `-tk` options could be renamed too. SSL is dead :)

To provide backwards compatibility the options could still be supported, but not documented in the `--help` output.

**Comment by lgrahl** [comment]
This is fine by me although my personal opinion is that SSL is synonymous to TLS today and I don't believe it will ever change, see for example: https://docs.python.org/3/library/ssl.html

I'm pretty sure we can add an alias option in click but I don't think there's a way to hide a specific one. I'd be fine with just an alias.

**Comment by lgrahl** [comment]
Again, I'm fine if we change it but I personally don't really care. :sweat_smile:

**Comment by dbrgn** [comment]
Ok, I'll provide a PR sometime :)

**Comment by lgrahl** [comment]
Closed due to inactivity.

**Comment by rugk** [comment]
But, but, but… it's not "fixed". :expressionless:

**Comment by dbrgn** [comment]
I'll provide a PR.
