### ISSUE TITLE
Dropping a responder is not immediate (enough)

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-server-python#81]
When dropping a responder, there seems to be a small time frame where messages are still being received (and dispatched).

**Comment by lgrahl** [comment]
This is what happens:

1. The initiator drops the responder.
2. The server initiates closing the connection to the responder but the task loop is still running. It enqueues a `disconnect` message towards the initiator.
3. The responder sneaks in a message to be relayed to the initiator.
4. The initiator thinks it is a handshake attempt and tries to decrypt either a `token` or a `key` message. The decrypt attempt fails and the initiator drops the (already dropped) responder with a close code of `3005`.
5. The server ignores that request since it has already dropped the responder.
6. For an unknown reason, the client sends a message containing a responder ID of `0` (this validation happens in `server-auth`, `new-responder` and `drop-responder`, so realistically this can only be a `drop-responder` message).
7. The server closes the connection to the initiator with a protocol error.

What we can conclude:

- Step 2: Sneaking in a relay message when the responder has already dropped is clearly a bug.
- Step 6: There must be a bug in the client library as well that results in two `drop-responder` messages sent after another and one of them containing an invalid responder ID (`0` - possibly an implicit conversion of `null` or `undefined`).

Open questions:

- Step 1: When and why does this happen in Threema Web?
- Step 4: Should the initiator proceed with the handshake without "permission" from the user application? What would happen in case the handshake completes? What does the spec say?

We should try to reproduce this with client and server together and then add a test in both client and server separately (if possible).

/cc @dbrgn

**Comment by dbrgn** [comment]
Nice debug session! :slightly_smiling_face: :+1:
